:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
      - GOOS: darwin
        GOARCH: amd64
.travis.yml:
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: B/rDRwmQXhsNFD0PHF3EmzcOHnq8EOdqVBSWS62KdYpVpcwBHqMcR+GdBhF4FcQWEcWzn31eYHndF68cctxx/AGi/r/B9d2c7IKQAavnvyJEkuytPd67Ib3tsvuWVP9TugDqAMLZbx5MXYCtJBbogs8v5VW1JwjOiWpIlDCQ2A0HuRmUYwaX3cpsUgOzyYy/yBBiQeVgTxrMHHFLYrukKdUcDbHsUuuKVyvSVcuuMbQ8EdL9YzlJoxGolNjg/m1KHOVkAs953KRjVKVBZ0W8jIxC5N3uzeVNfNrQGwaZalEbtIRnqpFGX0/ThxeDw5s9ReggPVnpifqZnYh24TOjvBs46S7vaAbej+7LXyxbuAVnMBFSHpY3LJV1UovFTO6s2Lnyi/Z3laGORmiAur5ZEZR/RTAI6yPH/EwEcWOEBC7KXLICGNyr4jRg1tTa5ari/rTou46zfFcK4v3UOsJCC9hPy7xAcLJ+kLxtjAjswfeNUIjfkgV/fFwTb0pZiaCqmOD2/qjY90r3v8Vw90thB1V0ywXmeCGXHasUQ506pnoqRxaNTnpudJOmejQgpg946J2QGEXWN/92aG4ZVtXVuN0Oip1TDbgIYEcR3L/qhRAeWs99Q9wlTEhlfSQclSiCa9plB07p4vbWqnssDOG1ziQtZRc8oaeEC9294fWx3Es=
    api_key:
      secure: es4I/9tkjFfuVGP60d4f0KlOw6Ma24jocyWeST7U+biGRX67RwtTVU6YMIHnSHC7jqV9i/C4iggflbJRP2zj9Uny/jAG3J4N9Z9LOap7Vcm3HLHEiq9VUoZwNTdDy4tgeC5y3XX20vDHVwyWjoYXcJQ+EQI0ELaSnmfK8pavIuzBzcYF+8Xva63VjaCbLMiMKM64xMHJnktsfTUUKxPpD04iqDQKDJt7nW5JXkcJKNnh3NGH11XuxaA96KJLlqEZXI0KjsWfV8Kgk9LcqJjzdqe0KS6nIGCtbiCihRrHkEe+x3VQeO5pFfypDmGSvJ2CNx94KaITJ53RkyHK4L+uXrEQPHCXVD7MozJV/tVhFRvP5Yn2vsXJc+24pmCRCCA8vO8W3IkakdU9AshnLngnhxqM2J8Y+6xw3fwdrBaSgRlFAiRIFjyurbaIeqC68G8GtEBaBViqVVEEHr1We9HhvY/QByJv+Rl5/m3abeO6HMdPIFKwDWu0oHHM9bwge0kN2arwIsCT4cjNrVNxetdEnO7yzDXIRHRQXRBvXPAUrtyRLHOCmm+6TCse6MG6A+mO7VuUw6TGKZGdJ0QCYpe/64/MGXnnaQiofkG1MRL5/rtUgYqI9IM+WLRpwrBjxrcGM456Kre68uRqAXmy3XxsuTd94MEzRmwcHkI5MUPlZ/s=
scripts/deps.sh:
  packages:
    - github.com/smartystreets/goconvey # NOTE: this should be moved to godep/glide
    - github.com/stretchr/testify/mock
